<?php

namespace App\Services\Assets;

/**
 * MAIN BANNER IMAGES DIMENSION
 */
if(!defined('MAIN_BANNER_IMAGES_SIZE')) define('MAIN_BANNER_IMAGES_SIZE', 1000);

if(!defined('MAIN_BANNER_WIDTH')) define('MAIN_BANNER_WIDTH', 1920);
if(!defined('MAIN_BANNER_HEIGHT')) define('MAIN_BANNER_HEIGHT', 763);

/**
 * NEWS IMAGES DIMENSION
 */
if(!defined('NEWS_IMAGES_SIZE')) define('NEWS_IMAGES_SIZE', 1000);

if(!defined('NEWS_THUMBNAIL_WIDTH')) define('NEWS_THUMBNAIL_WIDTH', 577);
if(!defined('NEWS_THUMBNAIL_HEIGHT')) define('NEWS_THUMBNAIL_HEIGHT', 305);

if(!defined('NEWS_IMAGES_WIDTH')) define('NEWS_IMAGES_WIDTH', 930);
if(!defined('NEWS_IMAGES_HEIGHT')) define('NEWS_IMAGES_HEIGHT', 493);

/**
 * EVENT IMAGES DIMENSION
 */
if(!defined('EVENT_IMAGES_SIZE')) define('EVENT_IMAGES_SIZE', 1000);

if(!defined('EVENT_THUMBNAIL_WIDTH')) define('EVENT_THUMBNAIL_WIDTH', 577);
if(!defined('EVENT_THUMBNAIL_HEIGHT')) define('EVENT_THUMBNAIL_HEIGHT', 305);

if(!defined('EVENT_IMAGES_WIDTH')) define('EVENT_IMAGES_WIDTH', 930);
if(!defined('EVENT_IMAGES_HEIGHT')) define('EVENT_IMAGES_HEIGHT', 493);


/**
 * COMPANY HISTORY FILE SIZE
 */
if(!defined('COMPANY_HISTORY_SIZE')) define('COMPANY_HISTORY_SIZE', 12000);


/**
 * GREEN PAGES DIMENSION
 */
if(!defined('GREEN_PAGES_SIZE')) define('GREEN_PAGES_SIZE', 1000);

if(!defined('GREEN_PAGES_THUMBNAIL_WIDTH')) define('GREEN_PAGES_THUMBNAIL_WIDTH', 460);
if(!defined('GREEN_PAGES_THUMBNAIL_HEIGHT')) define('GREEN_PAGES_THUMBNAIL_HEIGHT', 160);

if(!defined('GREEN_PAGES_IMAGES_WIDTH')) define('GREEN_PAGES_IMAGES_WIDTH', 930);
if(!defined('GREEN_PAGES_IMAGES_HEIGHT')) define('GREEN_PAGES_IMAGES_HEIGHT', 493);

/**
 * INVESTMENT SERVICES DIMENSION
 */
if(!defined('INVESTMENT_SERVICES_IMAGES_SIZE')) define('INVESTMENT_SERVICES_IMAGES_SIZE', 1000);

if(!defined('INVESTMENT_SERVICES_THUMBNAIL_WIDTH')) define('INVESTMENT_SERVICES_THUMBNAIL_WIDTH', 692);
if(!defined('INVESTMENT_SERVICES_THUMBNAIL_HEIGHT')) define('INVESTMENT_SERVICES_THUMBNAIL_HEIGHT', 381);

if(!defined('INVESTMENT_SERVICES_IMAGES_WIDTH')) define('INVESTMENT_SERVICES_IMAGES_WIDTH', 930);
if(!defined('INVESTMENT_SERVICES_IMAGES_HEIGHT')) define('INVESTMENT_SERVICES_IMAGES_HEIGHT', 493);