<?php

namespace App\Services\Assets;

/**
 * MAIN BANNER IMAGES DIMENSION
 */
if(!defined('MAIN_BANNER_IMAGES_SIZE')) define('MAIN_BANNER_IMAGES_SIZE', 1000);

if(!defined('MAIN_BANNER_WIDTH')) define('MAIN_BANNER_WIDTH', 1244);
if(!defined('MAIN_BANNER_HEIGHT')) define('MAIN_BANNER_HEIGHT', 829);

if(!defined('MAIN_BANNER_COMPANY_WIDTH')) define('MAIN_BANNER_COMPANY_WIDTH', 1920);
if(!defined('MAIN_BANNER_COMPANY_HEIGHT')) define('MAIN_BANNER_COMPANY_HEIGHT', 763);

/**
 * NEWS IMAGES DIMENSION
 */
if(!defined('NEWS_IMAGES_SIZE')) define('NEWS_IMAGES_SIZE', 1000);

if(!defined('NEWS_THUMBNAIL_WIDTH')) define('NEWS_THUMBNAIL_WIDTH', 577);
if(!defined('NEWS_THUMBNAIL_HEIGHT')) define('NEWS_THUMBNAIL_HEIGHT', 305);

if(!defined('NEWS_IMAGES_WIDTH')) define('NEWS_IMAGES_WIDTH', 930);
if(!defined('NEWS_IMAGES_HEIGHT')) define('NEWS_IMAGES_HEIGHT', 493);

/**
 * EVENT IMAGES DIMENSION
 */
if(!defined('EVENT_IMAGES_SIZE')) define('EVENT_IMAGES_SIZE', 1000);

if(!defined('EVENT_THUMBNAIL_WIDTH')) define('EVENT_THUMBNAIL_WIDTH', 577);
if(!defined('EVENT_THUMBNAIL_HEIGHT')) define('EVENT_THUMBNAIL_HEIGHT', 305);

if(!defined('EVENT_IMAGES_WIDTH')) define('EVENT_IMAGES_WIDTH', 930);
if(!defined('EVENT_IMAGES_HEIGHT')) define('EVENT_IMAGES_HEIGHT', 493);


/**
 * COMPANY HISTORY FILE SIZE
 */
if(!defined('COMPANY_HISTORY_SIZE')) define('COMPANY_HISTORY_SIZE', 12000);


/**
 * GREEN PAGES DIMENSION
 */
if(!defined('GREEN_PAGES_SIZE')) define('GREEN_PAGES_SIZE', 1000);

if(!defined('GREEN_PAGES_THUMBNAIL_WIDTH')) define('GREEN_PAGES_THUMBNAIL_WIDTH', 460);
if(!defined('GREEN_PAGES_THUMBNAIL_HEIGHT')) define('GREEN_PAGES_THUMBNAIL_HEIGHT', 160);

if(!defined('GREEN_PAGES_IMAGES_WIDTH')) define('GREEN_PAGES_IMAGES_WIDTH', 930);
if(!defined('GREEN_PAGES_IMAGES_HEIGHT')) define('GREEN_PAGES_IMAGES_HEIGHT', 493);

/**
 * INVESTMENT SERVICES DIMENSION
 */
if(!defined('INVESTMENT_SERVICES_IMAGES_SIZE')) define('INVESTMENT_SERVICES_IMAGES_SIZE', 1000);

if(!defined('INVESTMENT_SERVICES_THUMBNAIL_WIDTH')) define('INVESTMENT_SERVICES_THUMBNAIL_WIDTH', 692);
if(!defined('INVESTMENT_SERVICES_THUMBNAIL_HEIGHT')) define('INVESTMENT_SERVICES_THUMBNAIL_HEIGHT', 381);

if(!defined('INVESTMENT_SERVICES_IMAGES_WIDTH')) define('INVESTMENT_SERVICES_IMAGES_WIDTH', 930);
if(!defined('INVESTMENT_SERVICES_IMAGES_HEIGHT')) define('INVESTMENT_SERVICES_IMAGES_HEIGHT', 493);

// INVESTMENT SERVICES ENERGY CONSEREVATION DIMENSION

if(!defined('ENERGY_CONSEREVATION_THUMBNAIL_WIDTH')) define('ENERGY_CONSEREVATION_THUMBNAIL_WIDTH', 692);
if(!defined('ENERGY_CONSEREVATION_THUMBNAIL_HEIGHT')) define('ENERGY_CONSEREVATION_THUMBNAIL_HEIGHT', 381);

/**
 * RESOURCES WHITE PAPERS
 */
if(!defined('WHITE_PAPERS_FILE_UPLOAD_SIZE')) define('WHITE_PAPERS_FILE_UPLOAD_SIZE', 10000);
if(!defined('WHITE_PAPERS_IMAGES_SIZE')) define('WHITE_PAPERS_IMAGES_SIZE', 1000);
if(!defined('WHITE_PAPERS_FILE_SIZE')) define('WHITE_PAPERS_FILE_SIZE', 1000);

if(!defined('WHITE_PAPERS_THUMBNAIL_WIDTH')) define('WHITE_PAPERS_THUMBNAIL_WIDTH', 505);
if(!defined('WHITE_PAPERS_THUMBNAIL_HEIGHT')) define('WHITE_PAPERS_THUMBNAIL_HEIGHT', 377);
/**
 * RESOURCES TOOLS
 */
if(!defined('TOOLS_IMAGES_SIZE')) define('TOOLS_IMAGES_SIZE', 100000);
if(!defined('TOOLS_FILE_SIZE')) define('TOOLS_FILE_SIZE', 1000);

if(!defined('TOOLS_THUMBNAIL_WIDTH')) define('TOOLS_THUMBNAIL_WIDTH', 110);
if(!defined('TOOLS_THUMBNAIL_HEIGHT')) define('TOOLS_THUMBNAIL_HEIGHT', 110);

/**
 * INFORMATION SERVICES
 * INDUSTRY
 */
if(!defined('INDUSTRY_IMAGES_SIZE')) define('INDUSTRY_IMAGES_SIZE', 1000);

if(!defined('INDUSTRY_THUMBNAIL_WIDTH')) define('INDUSTRY_THUMBNAIL_WIDTH', 800);
if(!defined('INDUSTRY_THUMBNAIL_HEIGHT')) define('INDUSTRY_THUMBNAIL_HEIGHT', 462);